image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:

  - ./artifacts/app-mbank.jar

build_script:
  - ./gradlew test --info
  - name: Grant execute permission for gradlew
    run: chmod +x gradlew