image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:

  - java -jar ./artifacts/app-mbank.jar &



  - name: Grant execute permission for gradlew
    run: chmod +x gradlew

build_script:
  - ./gradlew test --info